# After staring container, don't forget to install db :
#   docker exec -it airnotifier python /airnotifier/install.py

version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/tmp/mongo/mongo.log
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/log:/tmp/mongo
    command: mongod --logpath=/dev/null # --quiet
  airnotifier:
    links:
      - mongodb
    depends_on:
      - mongodb
    build: .
    container_name: airnotifier
    volumes:
      - ./certs:/var/airnotifier/pemdir
      - ./logs:/var/log/airnotifier
    ports:
      - 8801:8801
    environment:
      - MONGO_SERVER=mongodb
      - MONGO_PORT=27017
